version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "monthly"
  - package-ecosystem: "uv"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "monthly"