# Copyright (C) 2025 Crash Override, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the FSF, either version 3 of the License, or (at your option) any later version.
# See the LICENSE file in the root of this repository for full license text or
# visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

[tool.pylint.main]

# Files or directories to be skipped. They should be base names, not paths.
ignore = [".venv", "dist", "build", "wheels"]

[tool.pylint."messages control"]
disable = ["missing-function-docstring", "missing-module-docstring", "missing-class-docstring", "too-many-arguments", "too-many-positional-arguments", "R0801"]
