###########################
## Environment Variables ##
###########################

TARGET_IDENTIFIER_ENVVAR = "OCULAR_TARGET_IDENTIFIER"
TARGET_VERSION_ENVVAR = "OCULAR_TARGET_VERSION"
TARGET_DOWNLOADER_ENVVAR = "OCULAR_TARGET_DOWNLOADER"

PROFILE_NAME_ENVVAR = "OCULAR_PROFILE_NAME"
PIPELINE_ID_ENVVAR = "OCULAR_PIPELINE_ID"

RESULTS_DIR_ENVVAR = "OCULAR_RESULTS_DIR"
TARGET_DIR_ENVVAR = "APSM_TARGET_DIR"

API_BASE_URL_ENVVAR = "OCULAR_API_BASE_URL"
CONTEXT_NAME_ENVVAR = "APSM_CONTEXT_NAME"

SERVICETOKEN_PATH_ENVVAR = "OCULAR_SERVICE_ACCOUNT_TOKEN_PATH"

CRAWLER_NAME_ENVVAR = "OCULAR_CRAWLER_NAME"

UPLOADER_NAME_ENVVAR = "OCULAR_UPLOADER_NAME"
