###########################
## Environment Variables ##
###########################

TARGET_IDENTIFIER_ENVVAR = "ASPM_TARGET_IDENTIFIER"
TARGET_VERSION_ENVVAR = "ASPM_TARGET_VERSION"
TARGET_DOWNLOADER_ENVVAR = "ASPM_TARGET_DOWNLOADER"

PROFILE_NAME_ENVVAR = "ASPM_PROFILE_NAME"
PIPELINE_ID_ENVVAR = "ASPM_PIPELINE_ID"

RESULTS_DIR_ENVVAR = "ASPM_RESULTS_DIR"
TARGET_DIR_ENVVAR = "APSM_TARGET_DIR"

API_BASE_URL_ENVVAR = "ASPM_API_BASE_URL"
CONTEXT_NAME_ENVVAR = "APSM_CONTEXT_NAME"

SERVICETOKEN_PATH_ENVVAR = "ASPM_SERVICE_ACCOUNT_TOKEN_PATH"

CRAWLER_NAME_ENVVAR = "ASPM_CRAWLER_NAME"

UPLOADER_NAME_ENVVAR = "ASPM_UPLOADER_NAME"
